import fs from "fs";
import fsp from "fs/promises";
import path from "path";
import OpenAI from "openai";
import { randomUUID } from "crypto";
import { spawn } from "child_process";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

const SUBS_DIR = path.join(process.cwd(), "tmp", "subs");

async function ensureDir(dir: string) {
  try {
    await fsp.mkdir(dir, { recursive: true });
  } catch {
    // ignore
  }
}

// ---- Types for Whisper verbose_json ----
type WhisperWord = {
  word: string;
  start: number;
  end: number;
};

type WhisperSegment = {
  id?: number;
  start: number;
  end: number;
  text: string;
  words?: WhisperWord[];
};

type WhisperVerboseResponse = {
  text: string;
  duration?: number;
  segments: WhisperSegment[];
};

export type CaptionStyle = "boldYellow" | "subtle" | "karaoke";

export type CaptionDraftWord = {
  text: string;
  startSec: number;
  endSec: number;
};

export type CaptionDraftChunk = {
  id: string;
  startSec: number;
  endSec: number;
  text: string;
  words?: CaptionDraftWord[];
};

export type CaptionDraftClip = {
  clipIndex: number;
  chunks: CaptionDraftChunk[];
};

const DEFAULT_FONT = "Inter";

// ===== Styling knobs =====
const CHUNK_SIZE = 4;
const LINE_FADE_IN_MS = 40;
const LINE_FADE_OUT_MS = 80;
const KARAOKE_POP_SCALE = 118;
const KARAOKE_POP_IN_MS = 70;
const KARAOKE_POP_OUT_MS = 80;

// Helpers
function secondsToAssTime(sec: number): string {
  if (sec < 0) sec = 0;
  const hours = Math.floor(sec / 3600);
  const minutes = Math.floor((sec % 3600) / 60);
  const seconds = Math.floor(sec % 60);
  const centiseconds = Math.round((sec - Math.floor(sec)) * 100);

  const pad2 = (n: number) => n.toString().padStart(2, "0");
  const pad2c = (n: number) => n.toString().padStart(2, "0");

  return `${hours}:${pad2(minutes)}:${pad2(seconds)}.${pad2c(centiseconds)}`;
}

function synthesizeDraftWordsFromChunkText(chunk: CaptionDraftChunk): CaptionDraftWord[] {
  const raw = normalizeText(chunk.text || "");
  if (!raw) return [];

  const tokens = raw.split(" ").filter(Boolean);
  if (!tokens.length) return [];

  const totalDur = Math.max(chunk.endSec - chunk.startSec, 0.2);
  const perWord = totalDur / tokens.length;

  return tokens.map((token, index) => {
    const startSec = chunk.startSec + index * perWord;
    const endSec =
      index === tokens.length - 1 ? chunk.endSec : chunk.startSec + (index + 1) * perWord;

    return {
      text: token,
      startSec,
      endSec,
    };
  });
}

function clamp(n: number, min: number, max: number) {
  return Math.max(min, Math.min(max, n));
}

function normalizeText(raw: string): string {
  return (raw ?? "").replace(/\s+/g, " ").trim();
}

function safeAssText(raw: string): string {
  return (raw ?? "").replace(/\r?\n/g, "\\N").replace(/\s+/g, " ").trim();
}

function buildAssHeader(style: CaptionStyle, fontName = DEFAULT_FONT): string {
  const playResX = 1080;
  const playResY = 1920;

  const styleLine = buildAssStyleLine(style, fontName);

  return `[Script Info]
; Script generated by Hookify
ScriptType: v4.00+
PlayResX: ${playResX}
PlayResY: ${playResY}
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
${styleLine}

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;
}

function buildAssStyleLine(style: CaptionStyle, fontName: string): string {
  const base = {
    Name: "Default",
    Fontname: fontName,
    Fontsize: 56,
    PrimaryColour: "&H00FFFFFF&",
    SecondaryColour: "&H00FFFFFF&",
    OutlineColour: "&HAA000000&",
    BackColour: "&H00000000&",
    Bold: 1,
    Italic: 0,
    Underline: 0,
    StrikeOut: 0,
    ScaleX: 100,
    ScaleY: 100,
    Spacing: 0,
    Angle: 0,
    BorderStyle: 1,
    Outline: 4,
    Shadow: 2,
    Alignment: 2,
    MarginL: 80,
    MarginR: 80,
    MarginV: 285,
    Encoding: 1,
  };

  if (style === "subtle") {
    return (
      "Style: " +
      [
        base.Name,
        base.Fontname,
        52,
        "&H00FFFFFF&",
        "&H00FFFFFF&",
        "&H99000000&",
        "&H00000000&",
        0,
        0,
        0,
        0,
        base.ScaleX,
        base.ScaleY,
        0,
        0,
        1,
        3,
        2,
        2,
        base.MarginL,
        base.MarginR,
        130,
        base.Encoding,
      ].join(",")
    );
  }

  if (style === "boldYellow") {
    return (
      "Style: " +
      [
        base.Name,
        base.Fontname,
        64,
        "&H0000FFFF&",
        "&H00FFFFFF&",
        "&HEE000000&",
        "&H00000000&",
        1,
        0,
        0,
        0,
        base.ScaleX,
        base.ScaleY,
        0,
        0,
        1,
        7,
        4,
        2,
        base.MarginL,
        base.MarginR,
        120,
        base.Encoding,
      ].join(",")
    );
  }

  return (
    "Style: " +
    [
      "Default",
      fontName,
      74,
      "&H00FFFFFF&",
      "&H00FFD200&",
      "&HDD000000&",
      "&H00000000&",
      1,
      0,
      0,
      0,
      100,
      100,
      0,
      0,
      1,
      4,
      2,
      2,
      80,
      80,
      120,
      1,
    ].join(",")
  );
}

function lineFade(): string {
  return `{\\fad(${LINE_FADE_IN_MS},${LINE_FADE_OUT_MS})}`;
}

async function runCmd(cmd: string, args: string[], logPrefix: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args);
    let stderr = "";

    proc.stderr.on("data", (d) => {
      stderr += d.toString();
    });

    proc.on("error", reject);

    proc.on("close", (code) => {
      if (code === 0) resolve();
      else {
        reject(new Error(`[${logPrefix}] ${cmd} exited with ${code}\n${stderr}`));
      }
    });
  });
}

async function extractTinyAudioForWhisper(videoPath: string): Promise<string> {
  const AUDIO_DIR = path.join(process.cwd(), "tmp", "audio");
  await ensureDir(AUDIO_DIR);

  const outPath = path.join(AUDIO_DIR, `${randomUUID()}.mp3`);

  const args = [
    "-y",
    "-i",
    videoPath,
    "-map",
    "0:a:0?",
    "-vn",
    "-ac",
    "1",
    "-ar",
    "16000",
    "-c:a",
    "libmp3lame",
    "-b:a",
    "24k",
    outPath,
  ];

  await runCmd("ffmpeg", args, "extractTinyAudioForWhisper");
  await fsp.access(outPath);

  const stat = await fsp.stat(outPath);

  if (stat.size < 1024) {
    throw new Error("No audio track or extracted audio too small for Whisper");
  }

  const MAX_BYTES = 24 * 1024 * 1024;

  if (stat.size > MAX_BYTES) {
    const outPath2 = path.join(AUDIO_DIR, `${randomUUID()}.mp3`);
    const args2 = [
      "-y",
      "-i",
      videoPath,
      "-map",
      "0:a:0?",
      "-vn",
      "-ac",
      "1",
      "-ar",
      "16000",
      "-c:a",
      "libmp3lame",
      "-b:a",
      "16k",
      outPath2,
    ];

    await runCmd("ffmpeg", args2, "extractTinyAudioForWhisper_16k");
    await fsp.access(outPath2);
    await fsp.unlink(outPath).catch(() => {});
    return outPath2;
  }

  return outPath;
}

/**
 * If Whisper didn't give us word-level timestamps,
 * fabricate them evenly across the segment.
 */
function synthesizeWordsFromSegment(seg: WhisperSegment): WhisperWord[] {
  const raw = normalizeText(seg.text || "");
  if (!raw) return [];

  const tokens = raw.split(" ").filter(Boolean);
  if (!tokens.length) return [];

  const totalDur = Math.max(seg.end - seg.start, 0.5);
  const perWord = totalDur / tokens.length;

  const words: WhisperWord[] = [];
  let cursor = seg.start;

  for (const token of tokens) {
    const start = cursor;
    const end = cursor + perWord;
    words.push({ word: token, start, end });
    cursor = end;
  }

  return words;
}

function chunkWords(words: WhisperWord[], chunkSize = CHUNK_SIZE): WhisperWord[][] {
  const chunks: WhisperWord[][] = [];

  for (let i = 0; i < words.length; i += chunkSize) {
    const group = words.slice(i, i + chunkSize);
    if (group.length) chunks.push(group);
  }

  return chunks;
}

function wordsToDraftChunk(words: WhisperWord[]): CaptionDraftChunk | null {
  if (!words.length) return null;

  const normalizedWords: CaptionDraftWord[] = words
    .map((w) => ({
      text: normalizeText(w.word || ""),
      startSec: w.start,
      endSec: w.end,
    }))
    .filter((w) => w.text);

  if (!normalizedWords.length) return null;

  return {
    id: randomUUID(),
    startSec: normalizedWords[0].startSec,
    endSec: normalizedWords[normalizedWords.length - 1].endSec,
    text: normalizedWords.map((w) => w.text).join(" "),
    words: normalizedWords,
  };
}

function buildDraftChunksFromSegment(seg: WhisperSegment): CaptionDraftChunk[] {
  const words = seg.words?.length ? seg.words : synthesizeWordsFromSegment(seg);
  if (!words.length) return [];

  return chunkWords(words)
    .map(wordsToDraftChunk)
    .filter((chunk): chunk is CaptionDraftChunk => !!chunk);
}

function buildKaraokeTextFromDraftChunk(chunk: CaptionDraftChunk): string {
  const normalizedChunkText = normalizeText(chunk.text || "");
  const normalizedWordsText = (chunk.words ?? []).map((w) => normalizeText(w.text)).join(" ");

  const words =
    chunk.words?.length && normalizedWordsText === normalizedChunkText
      ? chunk.words
      : synthesizeDraftWordsFromChunkText(chunk);

  let assText = "";
  let cursorMs = 0;

  for (const w of words) {
    const rawWord = safeAssText(w.text || "");
    if (!rawWord) continue;

    const durSec = Math.max(0.03, w.endSec - w.startSec);
    const durCs = Math.max(1, Math.round(durSec * 100));
    const durMs = durCs * 10;

    const wordStartMs = cursorMs;
    const wordEndMs = cursorMs + durMs;

    const popInEnd = Math.min(wordStartMs + KARAOKE_POP_IN_MS, wordEndMs);
    const popOutStart = Math.max(wordEndMs - KARAOKE_POP_OUT_MS, wordStartMs);
    const popScale = clamp(KARAOKE_POP_SCALE, 105, 140);

    if (assText) assText += " ";

    assText +=
      `{\\k${durCs}}` +
      `{\\t(${wordStartMs},${popInEnd},\\fscx${popScale}\\fscy${popScale})` +
      `\\t(${popOutStart},${wordEndMs},\\fscx100\\fscy100)}` +
      `${rawWord}` +
      `{\\fscx100\\fscy100}`;

    cursorMs += durMs;
  }

  return assText.trim();
}

function applyInlineStyle(text: string, style: CaptionStyle) {
  if (style === "boldYellow") {
    return `{\\b1\\bord7\\shad4\\c&H0000FFFF&}${text}`;
  }

  if (style === "subtle") {
    return `{\\b0\\bord3\\shad2\\c&H00FFFFFF&}${text}`;
  }

  return text;
}

function buildDialogueTextFromDraftChunk(
  chunk: CaptionDraftChunk,
  captionStyle: CaptionStyle,
): string {
  if (captionStyle === "karaoke") {
    return `${lineFade()}${buildKaraokeTextFromDraftChunk(chunk)}`;
  }

  return `${lineFade()}${applyInlineStyle(safeAssText(chunk.text), captionStyle)}`;
}

async function transcribeClipToDraft(
  clipPath: string,
  clipIndex: number,
): Promise<CaptionDraftClip> {
  const audioPath = await extractTinyAudioForWhisper(clipPath);

  try {
    const resp = (await openai.audio.transcriptions.create({
      model: "whisper-1",
      file: fs.createReadStream(audioPath),
      response_format: "verbose_json",
      timestamp_granularities: ["word", "segment"],
    })) as unknown as WhisperVerboseResponse;

    if (!resp.segments || resp.segments.length === 0) {
      return {
        clipIndex,
        chunks: [],
      };
    }

    const chunks = resp.segments.flatMap((seg) => buildDraftChunksFromSegment(seg));

    return {
      clipIndex,
      chunks,
    };
  } finally {
    await fsp.unlink(audioPath).catch(() => {});
  }
}

function draftClipToAss(
  draftClip: CaptionDraftClip,
  captionStyle: CaptionStyle,
  fontName: string,
): string {
  let ass = buildAssHeader(captionStyle, fontName);

  for (const chunk of draftClip.chunks) {
    const start = secondsToAssTime(chunk.startSec);
    const end = secondsToAssTime(chunk.endSec);
    const text = buildDialogueTextFromDraftChunk(chunk, captionStyle);

    const dialogue = ["Dialogue: 0", start, end, "Default", "", "0", "0", "0", "", text].join(",");

    ass += dialogue + "\n";
  }

  return ass;
}

/**
 * NEW:
 * Generate JSON drafts that the user can edit later.
 */
export async function generateCaptionDraftsForClips(clips: string[]): Promise<CaptionDraftClip[]> {
  await ensureDir(SUBS_DIR);

  const drafts: CaptionDraftClip[] = [];

  for (let i = 0; i < clips.length; i++) {
    const clipPath = clips[i];

    try {
      const draft = await transcribeClipToDraft(clipPath, i);
      drafts.push(draft);
    } catch (err) {
      console.error("[generateCaptionDraftsForClips] Failed for clip:", clipPath, err);

      drafts.push({
        clipIndex: i,
        chunks: [],
      });
    }
  }

  return drafts;
}

/**
 * NEW:
 * Build ASS files from already existing drafts.
 */
export async function generateSubtitlesFromDrafts(
  drafts: CaptionDraftClip[],
  clips: string[],
  options?: { captionStyle?: CaptionStyle; fontName?: string },
): Promise<string[]> {
  await ensureDir(SUBS_DIR);

  const captionStyle = options?.captionStyle ?? "karaoke";
  const fontName = options?.fontName ?? DEFAULT_FONT;

  const subtitleFiles: string[] = [];

  for (let i = 0; i < clips.length; i++) {
    const clipPath = clips[i];
    const base = path.basename(clipPath, path.extname(clipPath));
    const assPath = path.join(SUBS_DIR, `${base}.ass`);

    const draft = drafts.find((d) => d.clipIndex === i) ?? {
      clipIndex: i,
      chunks: [],
    };

    const ass = draftClipToAss(draft, captionStyle, fontName);
    await fsp.writeFile(assPath, ass, "utf8");
    subtitleFiles.push(assPath);
  }

  return subtitleFiles;
}

/**
 * COMPAT:
 * Old flow still works.
 * Internally: draft -> ass
 */
export async function generateSubtitlesForClips(
  clips: string[],
  options?: { captionStyle?: CaptionStyle; fontName?: string },
): Promise<string[]> {
  const drafts = await generateCaptionDraftsForClips(clips);
  return generateSubtitlesFromDrafts(drafts, clips, options);
}
