"use client";

import { useEffect, useState } from "react";
import type { Job } from "@lib/jobsStore";

export default function ShortsGalleryPage() {
    const [jobs, setJobs] = useState<Job[]>([]);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        async function load() {
            setLoading(true);
            try {
                const res = await fetch("/api/jobs");
                const data = await res.json();
                setJobs(data.jobs ?? []);
            } finally {
                setLoading(false);
            }
        }
        load();
    }, []);

    const shorts = jobs.flatMap((job) =>
        (job.captionedClips ?? []).map((clipUrl, idx) => ({
            clipUrl,
            thumbUrl: job.captionedThumbs?.[idx],
            jobId: job.id,
            createdAt: job.createdAt,
            source: job.source,
            aspect: job.aspect,
        }))
    );

    return (
        <main className="mx-auto min-h-screen max-w-6xl px-4 py-8">
            <header className="mb-6 flex items-center justify-between gap-4">
                <div>
                    <h1 className="text-2xl font-semibold tracking-tight text-slate-50">
                        Shorts Gallery
                    </h1>
                    <p className="mt-1 text-sm text-slate-400">
                        All shorts generated by Shortify, across all jobs.
                    </p>
                </div>
                {loading && (
                    <div className="text-xs text-sky-400">Loading shorts...</div>
                )}
            </header>

            {shorts.length === 0 ? (
                <p className="text-sm text-slate-500">
                    No shorts yet. Create some from the main dashboard.
                </p>
            ) : (
                <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
                    {shorts.map((short, idx) => (
                        <div
                            key={`${short.jobId}-${idx}`}
                            className="group flex flex-col overflow-hidden rounded-2xl border border-slate-800 bg-slate-950/70 shadow-lg transition-transform duration-200 hover:-translate-y-1 hover:border-sky-500/70"
                        >
                            <div className="relative aspect-[9/16] overflow-hidden bg-slate-900">
                                {short.thumbUrl ? (
                                    <img
                                        src={short.thumbUrl}
                                        alt="Short thumbnail"
                                        className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
                                    />
                                ) : (
                                    <div className="flex h-full items-center justify-center text-xs text-slate-500">
                                        No thumbnail
                                    </div>
                                )}

                                <div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-black/20 opacity-80" />
                            </div>

                            <div className="flex flex-1 flex-col justify-between p-3">
                                <div className="space-y-1">
                                    <div className="flex items-center justify-between gap-2 text-[11px] text-slate-400">
                    <span className="truncate font-mono text-[10px] text-slate-500">
                      {short.jobId.slice(0, 8)}…
                    </span>
                                        {short.aspect && (
                                            <span className="rounded-full bg-slate-900 px-2 py-0.5 text-[10px] uppercase text-slate-300">
                        {short.aspect === "vertical" ? "9:16" : "16:9"}
                      </span>
                                        )}
                                    </div>
                                    <div className="line-clamp-1 text-[12px] text-slate-200">
                                        {short.source}
                                    </div>
                                </div>

                                <div className="mt-3 flex gap-2">
                                    <a
                                        href={short.clipUrl}
                                        target="_blank"
                                        className="flex-1 rounded-full bg-sky-500 px-2 py-1.5 text-center text-[11px] font-semibold text-white transition hover:bg-sky-400"
                                    >
                                        Preview
                                    </a>
                                    <a
                                        href={short.clipUrl}
                                        download
                                        className="rounded-full border border-sky-500 px-2 py-1.5 text-[11px] font-semibold text-sky-400 transition hover:bg-sky-500/10"
                                    >
                                        Download
                                    </a>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </main>
    );
}
